$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:3
        },
        750:{
            items:5
        },
        1000:{
            items:5
        }
    }
})